version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network

volumes:
  pg_data:

networks:
  my_network:
    driver: bridge
